#!/bin/bash

echo "Step1:"
echo "wget -N --no-check-certificate -q -O install.sh "https://raw.githubusercontent.com/wulabing/Xray_onekey/nginx_forward/install.sh" && chmod +x install.sh && bash install.sh"
echo "Step2:"
echo "wget -N --no-check-certificate https://gitlab.com/rwkgyg/CFwarp/raw/main/CFwarp.sh && bash CFwarp.sh"
echo "Step3:"
echo "Turn to /etc/nginx/conf.d/"
echo "        #forbidden Scrapy"
echo "        if (\$http_user_agent ~* (Scrapy|Curl|HttpClient)) {"
echo "            return 403;"
echo "        }"
echo ""
echo "        if (\$http_user_agent ~ \"Bytespider|FeedDemon|JikeSpider|Indy Library|Alexa Toolbar|AskTbFXTV|AhrefsBot|CrawlDaddy|CoolpadWebkit|Java|Feedly|UniversalFeedParser|ApacheBench|Microsoft URL Control|Swiftbot|ZmEu|oBot|jaunty|Python-urllib|python-requests|lightDeckReports Bot|YYSpider|DigExt|YisouSpider|HttpClient|MJ12bot|heritrix|EasouSpider|Ezooms|baiduspider|360spider|haosouspider|googlebot|soso|bing|sogou|yahoo|sohu-search|yodao|YoudaoBot|robozilla|msnbot|MJ12bot|NHN|Twiceler|qihoobot|Baiduspider|Googlebot|Googlebot-Mobile|Googlebot-Image|Mediapartners-Google|Adsbot-Google|Feedfetcher-Google|Yahoo! Slurp|Yahoo! Slurp China|YoudaoBot|Sosospider|Sogou spider|Sogou web spider|MSNBot|ia_archiver|Tomato Bot|^$\" ) {"
echo ""
echo "            return 403;"
echo "        }"
echo ""
echo "        #forbidden not GET|HEAD|POST method access"
echo "         if (\$request_method !~ ^(GET|HEAD|POST)\$) {"
echo "            return 403;"
echo "        }"
echo ""
echo "        location / {"
echo "            proxy_pass https://vk.com;"
echo "        }"